name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Describe the solution you'd like
  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions or features considered
  - type: textarea
    attributes:
      label: Additional context

