name: link-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'

concurrency:
  group: linkcheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links in Markdown files
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --config lychee.toml **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
